name: Deploy Image Carousel to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NEW }}  # Correct token name
        app_location: "/"  # Location of static files
        output_location: "/"  # No build process, output is in root
        deployment_action: "upload"  # Perform the upload action
