name: Deploy Static Website to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NEW }}
        app_location: "/"  # Location of static files in the root directory
        output_location: "/"  # Output is in the root directory
        skip_app_build: true  # Skip Oryx build process as this is a static site
